os: linux
dist: focal

language: ruby
rvm: 3.0.2

cache: bundler

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
    - main

before_install:
  - nvm install node
  - ruby -v

install:
  - gem update --system
  - gem install webrick
  - gem install jekyll
  - gem install jekyll-redirect-from
  - npm install -g firebase-tools

before_script:
  - bundle exec jekyll build --incremental

script:
  # - firebase deploy --token "$FIREBASE_TOKEN"